name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-10.13

    steps:
    - uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version 
    - uses: actions/checkout@v3
    - name: Build
      run: swift run Runner 0 0 0
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: "/tmp/gena/results.csv"
        retention-days: 1
        
  ne_build:
    needs: build
    runs-on: macos-10.13
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: 774506700
          token: 1629447156:AAHtPQWzka0XpErG3VVzlt2FrRkmI3qbwpI
          message: Results is ready!
          document: results.csv
